// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fpixel.proto

package fpixels

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EmptyRequest) Validate() error {
	return nil
}
func (this *EmptyReply) Validate() error {
	return nil
}
func (this *ListSensorsResponse) Validate() error {
	for _, item := range this.Sensors {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Sensors", err)
			}
		}
	}
	return nil
}
func (this *SensorRawDataRequest) Validate() error {
	return nil
}
func (this *SensorRawDataResponse) Validate() error {
	return nil
}
func (this *ListDisplaysResponse) Validate() error {
	for _, item := range this.Displays {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Displays", err)
			}
		}
	}
	return nil
}
func (this *DrawRequest) Validate() error {
	return nil
}
func (this *Device) Validate() error {
	return nil
}
func (this *Display) Validate() error {
	if this.Device != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Device); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Device", err)
		}
	}
	return nil
}
